name: sweights-py312
channels:
  - conda-forge
dependencies:
  - hdf5
  - hepstats
  - hist
  - ipython
  - matplotlib
  - mplhep
  - numpy
  - pip
  - python==3.12
  - scipy
  - uproot
  - zfit
  - pip:
      - particle
      - snakemake
      - tables
      - uncertainties